const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI0NywidXNlcm5hbWUiOiJWaW5heSIsImlhdCI6MTcyNzc3ODQ3MH0.FeU-E-dGkQSNELUiEen0VjFm9RjJ9zZRDg20uxY7kKc"
const anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptZ2djYXZlY3lidHpodnZ5c2ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjY1NDEwMjEsImV4cCI6MjA0MjExNzAyMX0.X8u43LP8NjBNC8e0mw07eOhQiGXnCI4QjbkTQ7Nyk6s"
const supabase_url = "https://jmggcavecybtzhvvyseb.supabase.co"

const tokenForUserCredentialsVinay = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVmluYXkiLCJ2ZW5kb3JJZCI6OCwiaWF0IjoxNzMyNDExMDUyfQ.Ku5CHKAX-WCvt5HdFP6frJGfjSBbqTCsoicRbmCZ8ww"
const tokenForUserCredentialsDeepak = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGVlcGFrIiwidmVuZG9ySWQiOjUsImlhdCI6MTcyNzgyOTg5NX0.wCTH2Z3KoplJjX0ucIW5qbTFdyoymMYfr9ZQG7e3jh8"
const tokenForUserCredentailsJagadeesh = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmFnYWRlZXNoIiwidmVuZG9ySWQiOjYsImlhdCI6MTcyODEzMjMwOH0.2O51ywQXzzh-hR4LvqTgpeaPZ2RIeQa9ikkgK0IelWg"
const tokenForUserCredentailsHareesh =  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSGFyaXNoIiwidmVuZG9ySWQiOjcsImlhdCI6MTcyODEzMjQzOH0.AQkIu1tSEa6AO9K0eZ2scTxSEUFFFw0hrGBiPuJ8MCY"
